data:

  _target_: image_segmentation.data.datamodule.DataModule

  data_path: data/membrane

  stage: ~ # None, fit or test

  batch_size:
    train: 2
    val: 2
    test: 2

  resize:
      _target_: tensorflow.keras.layers.Resizing
      height: 572
      width: 572
      crop_to_aspect_ratio: False

  data_augmentation:
    random_flip:
      _target_: tensorflow.keras.layers.RandomFlip
      seed: 0
    random_translation:
      _target_: tensorflow.keras.layers.RandomTranslation
      seed: 0
      height_factor: 0.05
      width_factor: 0.05
      fill_mode: nearest
    random_rotation:
      _target_: tensorflow.keras.layers.RandomRotation
      seed: 0
      factor: 0.2
      fill_mode: nearest
    random_zoom:
      _target_: tensorflow.keras.layers.RandomZoom
      seed: 0
      height_factor: 0.05
      fill_mode: nearest

  val_percentage: 0.2

unet:
  structure:
    num_pooling: 4
    num_layers_before_pooling: 2
    initial_num_filters: 64
    pool_size: 2
    block_type:
      name: standard_block
      path:
        _target_: image_segmentation.models.tf_unet.unet_block.StandardBlock
      name_up: standard_up_block
      path_up:
        _target_: image_segmentation.models.tf_unet.unet_block.StandardUpBlock

  blocks:
    standard_block:
      kernel_size: 3
      padding: same
      kernel_initializer: he_normal
      activation: relu
      batch_norm: True

    standard_up_block:
      kernel_size: 2
      padding: same
      kernel_initializer: he_normal
      activation: relu

    final_block:
      _target_: image_segmentation.models.tf_unet.unet_block.FinalBlock
      kernel_size: 3
      padding: same
      kernel_initializer: he_normal
      activation: relu
